### ISSUE TITLE
No command was given

### ISSUE THREAD

**Issue by enragedtadpole** [cloudflare/GCS-Logshare-Setup-Script#2]
Receiving a 'No command was given' when executing main.sh - I am not sure what this means and it must be impacting my VM provisioning as there is nothing else being created, only the VM; no bucket, no cloud function and no BigQuery dataset or table.

https://user-images.githubusercontent.com/9005243/40042827-ce361e5c-5861-11e8-8ba0-c2e841dab740.png

**Comment by enragedtadpole** [comment]
I managed to fix this issue by installing Google Cloud SDK again on Ubuntu on Windows: https://www.techietown.info/2017/03/install-gsutil-centosubuntu/

I am now experiencing another issue with the data not flowing correctly which I have posted here:
https://support.cloudflare.com/hc/en-us/requests/1523344

**Comment by garrettgalow** [comment]
can you create an issue on the repo for what you are seeing: https://github.com/cloudflare/GCS-To-Big-Query
